services:
  # Backend API Service
  - type: web
    name: exoplanet-ai-backend
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      cd backend
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      cd backend
      gunicorn main:app --config gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 8001
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: CACHE_REDIS_URL
        fromService:
          type: redis
          name: exoplanet-ai-redis
          property: connectionString
      - key: NASA_API_KEY
        sync: false
      - key: NASA_ESA_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: ALLOWED_ORIGINS
        value: https://exoplanet-ai-frontend.onrender.com,http://localhost:5173,http://localhost:3000
    healthCheckPath: /api/v1/health

  # Redis Cache Service
  - type: redis
    name: exoplanet-ai-redis
    region: oregon
    plan: starter
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

  # Frontend Static Site (Optional - if deploying frontend separately)
  - type: web
    name: exoplanet-ai-frontend
    env: static
    region: oregon
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://exoplanet-ai-backend.onrender.com
