services:
  # Frontend Static Service
  - type: static
    name: exoplanet-ai-frontend
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://exoplanet-ai-backend.onrender.com

  # Backend API Service
  - type: web
    name: exoplanet-ai-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: cd backend && gunicorn main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120
    healthCheckPath: /api/v1/health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: NASA_API_KEY
        value: DEMO_KEY
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: ALLOWED_ORIGINS
        value: "https://exoplanet-ai-frontend.onrender.com,http://localhost:5173,http://localhost:3000"
    healthCheckPath: /api/v1/health
