name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: exoplanet_ai
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" 
          --health-interval 5s 
          --health-timeout 5s 
          --health-retries 20
    defaults:
      run:
        working-directory: Exoplanet_AI/apps/backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: Exoplanet_AI/apps/backend/package-lock.json
      - run: npm ci --ignore-scripts --no-audit --no-fund || npm i --ignore-scripts --no-audit --no-fund
      - name: Prisma generate
        run: npx prisma generate
      - name: Prisma migrate
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/exoplanet_ai?schema=public
        run: npx prisma migrate deploy
      - name: Seed database
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/exoplanet_ai?schema=public
        run: npm run seed
      - run: npm run typecheck
      - run: npm run lint --if-present
      - run: npm run build

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Exoplanet_AI/frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: Exoplanet_AI/frontend/package-lock.json
      - run: npm ci --ignore-scripts --no-audit --no-fund || npm i --ignore-scripts --no-audit --no-fund
      - run: npm run build

  e2e-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend
    defaults:
      run:
        working-directory: Exoplanet_AI/frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: Exoplanet_AI/frontend/package-lock.json
      - run: npm ci --ignore-scripts --no-audit --no-fund || npm i --ignore-scripts --no-audit --no-fund
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Vite preview
        run: npm run preview -- --port 5173 &
      - name: Wait for server
        run: npx wait-on http://localhost:5173
      - name: Run E2E tests
        run: npm run test:e2e


